// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package domain_name

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if !reflect.DeepEqual(a.ko.Spec.DomainNameConfigurations, b.ko.Spec.DomainNameConfigurations) {
		delta.Add("Spec.DomainNameConfigurations", a.ko.Spec.DomainNameConfigurations, b.ko.Spec.DomainNameConfigurations)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MutualTLSAuthentication, b.ko.Spec.MutualTLSAuthentication) {
		delta.Add("Spec.MutualTLSAuthentication", a.ko.Spec.MutualTLSAuthentication, b.ko.Spec.MutualTLSAuthentication)
	} else if a.ko.Spec.MutualTLSAuthentication != nil && b.ko.Spec.MutualTLSAuthentication != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.MutualTLSAuthentication.TruststoreURI, b.ko.Spec.MutualTLSAuthentication.TruststoreURI) {
			delta.Add("Spec.MutualTLSAuthentication.TruststoreURI", a.ko.Spec.MutualTLSAuthentication.TruststoreURI, b.ko.Spec.MutualTLSAuthentication.TruststoreURI)
		} else if a.ko.Spec.MutualTLSAuthentication.TruststoreURI != nil && b.ko.Spec.MutualTLSAuthentication.TruststoreURI != nil {
			if *a.ko.Spec.MutualTLSAuthentication.TruststoreURI != *b.ko.Spec.MutualTLSAuthentication.TruststoreURI {
				delta.Add("Spec.MutualTLSAuthentication.TruststoreURI", a.ko.Spec.MutualTLSAuthentication.TruststoreURI, b.ko.Spec.MutualTLSAuthentication.TruststoreURI)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MutualTLSAuthentication.TruststoreVersion, b.ko.Spec.MutualTLSAuthentication.TruststoreVersion) {
			delta.Add("Spec.MutualTLSAuthentication.TruststoreVersion", a.ko.Spec.MutualTLSAuthentication.TruststoreVersion, b.ko.Spec.MutualTLSAuthentication.TruststoreVersion)
		} else if a.ko.Spec.MutualTLSAuthentication.TruststoreVersion != nil && b.ko.Spec.MutualTLSAuthentication.TruststoreVersion != nil {
			if *a.ko.Spec.MutualTLSAuthentication.TruststoreVersion != *b.ko.Spec.MutualTLSAuthentication.TruststoreVersion {
				delta.Add("Spec.MutualTLSAuthentication.TruststoreVersion", a.ko.Spec.MutualTLSAuthentication.TruststoreVersion, b.ko.Spec.MutualTLSAuthentication.TruststoreVersion)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if !ackcompare.MapStringStringEqual(ToACKTags(a.ko.Spec.Tags), ToACKTags(b.ko.Spec.Tags)) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
